### ISSUE TITLE
ECG Stack Overflow in rare circumstances?

### ISSUE THREAD

**Issue by Norway174** [DyaMetR/holohud2#8]
I'm honestly not quite sure what was happening.

It was working fine, and I was customizing the HUD. I changed around the Vitality settings, and enabled the ECG component.
No issues. Later, I'd restart my Gmod. And when I started my singleplayer game, my game would freeze upon loading in.

After a few times of trying, I'd always freeze at the same spot. No freeze when I disable this addon. Also, no freeze when I disable all other addons, and only leave this one enabled.

So at first, I thought maybe there was an incompatibility. So I enable logging, to check the logs.

The last lines of log I see is this:
```
[D/GL4: Customizable Holographic HUD] table overflow
  1. insert - [C]:-1
   2. Add - lua/holohud2/components/ecg.lua:85
    3. Think - lua/holohud2/components/ecg.lua:266
     4. Think - lua/holohud2/elements/health/hudhealth.lua:322
      5. PreDraw - lua/holohud2/elements/health.lua:733
       6. fn - lua/holohud2/init.lua:192
        7. unknown - lua/ulib/shared/hook.lua:109


[D/GL4: Customizable Holographic HUD] table overflow
  1. insert - [C]:-1
   2. Add - lua/holohud2/components/ecg.lua:85
    3. Think - lua/holohud2/components/ecg.lua:266
     4. Think - lua/holohud2/elements/health/hudhealth.lua:322
      5. PreDraw - lua/holohud2/elements/health.lua:733
       6. fn - lua/holohud2/init.lua:192
        7. unknown - lua/ulib/shared/hook.lua:109
```

Seems the freeze happens when the Heartbeats table fills up, and is infinitely added.

I was able to fix it locally for myself, by simply adding a max beats.
To ensure it can't just keep adding it infinitely. If you're interested, here's the code changes I did. Feel free to copy.

![Image](https://github.com/user-attachments/assets/892d6ebf-d537-4436-a8c5-c86e2eda36b6)

As I said at the start, I've got no idea why it overflows when I have addons enabled vs when I don't. I don't have any other HUD addons installed. I uninstalled the previous H0L-D4. And, I was able to play just fine, with the default settings. It wasn't until I changed it, and enabled the ECG reader, and restarted my game, until it happened. Which kind of makes sense, considering the fix?

---

Also, overall, just wanted to say, amazing work on this project! I love previous version, and been using it as my main go-to HUD for everything. Even ended up making my own modules for it. (Just some shitty custom DarkRP modules.)

And this V2 version really ramps it up to 110%! I'm loving it so much!

- Thanks!

**Comment by DyaMetR** [comment]
Thank you for your kind words and the detailed report, I'll look into it and maybe follow your suggestion. Also, I'm really glad to hear you've found the API comfortable enough to make your own modules for it!

**Comment by DyaMetR** [comment]
Should be solved in 359d75146d31e61ef60349518ee59c7c8e38a83c. I'll wait a bit to see if it gets reported again before closing the issue.

**Comment by Norway174** [comment]
Hi again.
I'm unable to reopen the issue. But, it appears to not quite be fixed.
As it still happens. (Apologies it took so long to test it. I never updated until recently.)

I believe the `_shape` on this line: https://github.com/DyaMetR/holohud2/blob/1bea9c36f5587248b48f5961a3d51e14ec7c1f9c/lua/holohud2/components/ecg.lua#L84 is an error. And it should actually be `_cache`.

I switched it from _shape to _cache, and it works again for me in my testing.
